### ISSUE TITLE
Upgrading to Wagtail 2.13 errors

### ISSUE THREAD

**Issue by enzedonline** [wagtail/wagtail-localize#396]
I've upgraded my dev server to 2.13, getting a lot of warnings after migrating. Are there some extra migration steps needed? Well - not sure if this is general Wagtail issue or to do with Wagtail-Localize tbh

```
WARNINGS:
contact.FormField: (models.W042) Auto-created primary key used when not defining a primary key type, by default 'django.db.models.AutoField'.      
        HINT: Configure the DEFAULT_AUTO_FIELD setting or the ContactConfig.default_auto_field attribute to point to a subclass of AutoField, e.g. 
'django.db.models.BigAutoField'.
core.ServiceType: (models.W042) Auto-created primary key used when not defining a primary key type, by default 'django.db.models.AutoField'.       
        HINT: Configure the DEFAULT_AUTO_FIELD setting or the CoreConfig.default_auto_field attribute to point to a subclass of AutoField, e.g. 'django.db.models.BigAutoField'.
core.Testimonial: (models.W042) Auto-created primary key used when not defining a primary key type, by default 'django.db.models.AutoField'.       
        HINT: Configure the DEFAULT_AUTO_FIELD setting or the CoreConfig.default_auto_field attribute to point to a subclass of AutoField, e.g. 'django.db.models.BigAutoField'.
menu.AutofillMenuItem: (models.W042) Auto-created primary key used when not defining a primary key type, by default 'django.db.models.AutoField'.  
        HINT: Configure the DEFAULT_AUTO_FIELD setting or the MenuConfig.default_auto_field attribute to point to a subclass of AutoField, e.g. 'django.db.models.BigAutoField'.
menu.CompanyLogo: (models.W042) Auto-created primary key used when not defining a primary key type, by default 'django.db.models.AutoField'.       
        HINT: Configure the DEFAULT_AUTO_FIELD setting or the MenuConfig.default_auto_field attribute to point to a subclass of AutoField, e.g. 'django.db.models.BigAutoField'.
menu.LinkMenuItem: (models.W042) Auto-created primary key used when not defining a primary key type, by default 'django.db.models.AutoField'.      
        HINT: Configure the DEFAULT_AUTO_FIELD setting or the MenuConfig.default_auto_field attribute to point to a subclass of AutoField, e.g. 'django.db.models.BigAutoField'.
menu.Menu: (models.W042) Auto-created primary key used when not defining a primary key type, by default 'django.db.models.AutoField'.
        HINT: Configure the DEFAULT_AUTO_FIELD setting or the MenuConfig.default_auto_field attribute to point to a subclass of AutoField, e.g. 'django.db.models.BigAutoField'.
menu.SubMenuItem: (models.W042) Auto-created primary key used when not defining a primary key type, by default 'django.db.models.AutoField'.       
        HINT: Configure the DEFAULT_AUTO_FIELD setting or the MenuConfig.default_auto_field attribute to point to a subclass of AutoField, e.g. 'django.db.models.BigAutoField'.
site_settings.EmailSettings: (models.W042) Auto-created primary key used when not defining a primary key type, by default 'django.db.models.AutoField'.
        HINT: Configure the DEFAULT_AUTO_FIELD setting or the SiteSettingsConfig.default_auto_field attribute to point to a subclass of AutoField, 
e.g. 'django.db.models.BigAutoField'.
site_settings.EmailSignature: (models.W042) Auto-created primary key used when not defining a primary key type, by default 'django.db.models.AutoField'.
        HINT: Configure the DEFAULT_AUTO_FIELD setting or the SiteSettingsConfig.default_auto_field attribute to point to a subclass of AutoField, 
e.g. 'django.db.models.BigAutoField'.
site_settings.SocialMedia: (models.W042) Auto-created primary key used when not defining a primary key type, by default 'django.db.models.AutoField'.
        HINT: Configure the DEFAULT_AUTO_FIELD setting or the SiteSettingsConfig.default_auto_field attribute to point to a subclass of AutoField, 
e.g. 'django.db.models.BigAutoField'.
taggit.Tag: (models.W042) Auto-created primary key used when not defining a primary key type, by default 'django.db.models.AutoField'.
        HINT: Configure the DEFAULT_AUTO_FIELD setting or the TaggitAppConfig.default_auto_field attribute to point to a subclass of AutoField, e.g. 'django.db.models.BigAutoField'.
taggit.TaggedItem: (models.W042) Auto-created primary key used when not defining a primary key type, by default 'django.db.models.AutoField'.      
        HINT: Configure the DEFAULT_AUTO_FIELD setting or the TaggitAppConfig.default_auto_field attribute to point to a subclass of AutoField, e.g. 'django.db.models.BigAutoField'.
wagtail_localize.LocaleSynchronization: (models.W042) Auto-created primary key used when not defining a primary key type, by default 'django.db.models.AutoField'.
        HINT: Configure the DEFAULT_AUTO_FIELD setting or the WagtailLocalizeAppConfig.default_auto_field attribute to point to a subclass of AutoField, e.g. 'django.db.models.BigAutoField'.
wagtail_localize.OverridableSegment: (models.W042) Auto-created primary key used when not defining a primary key type, by default 'django.db.models.AutoField'.
        HINT: Configure the DEFAULT_AUTO_FIELD setting or the WagtailLocalizeAppConfig.default_auto_field attribute to point to a subclass of AutoField, e.g. 'django.db.models.BigAutoField'.
wagtail_localize.RelatedObjectSegment: (models.W042) Auto-created primary key used when not defining a primary key type, by default 'django.db.models.AutoField'.
        HINT: Configure the DEFAULT_AUTO_FIELD setting or the WagtailLocalizeAppConfig.default_auto_field attribute to point to a subclass of AutoField, e.g. 'django.db.models.BigAutoField'.
wagtail_localize.SegmentOverride: (models.W042) Auto-created primary key used when not defining a primary key type, by default 'django.db.models.AutoField'.
        HINT: Configure the DEFAULT_AUTO_FIELD setting or the WagtailLocalizeAppConfig.default_auto_field attribute to point to a subclass of AutoField, e.g. 'django.db.models.BigAutoField'.
wagtail_localize.String: (models.W042) Auto-created primary key used when not defining a primary key type, by default 'django.db.models.AutoField'.        HINT: Configure the DEFAULT_AUTO_FIELD setting or the WagtailLocalizeAppConfig.default_auto_field attribute to point to a subclass of AutoField, e.g. 'django.db.models.BigAutoField'.
wagtail_localize.StringSegment: (models.W042) Auto-created primary key used when not defining a primary key type, by default 'django.db.models.AutoField'.
        HINT: Configure the DEFAULT_AUTO_FIELD setting or the WagtailLocalizeAppConfig.default_auto_field attribute to point to a subclass of AutoField, e.g. 'django.db.models.BigAutoField'.
wagtail_localize.StringTranslation: (models.W042) Auto-created primary key used when not defining a primary key type, by default 'django.db.models.AutoField'.
        HINT: Configure the DEFAULT_AUTO_FIELD setting or the WagtailLocalizeAppConfig.default_auto_field attribute to point to a subclass of AutoField, e.g. 'django.db.models.BigAutoField'.
wagtail_localize.Template: (models.W042) Auto-created primary key used when not defining a primary key type, by default 'django.db.models.AutoField'.
        HINT: Configure the DEFAULT_AUTO_FIELD setting or the WagtailLocalizeAppConfig.default_auto_field attribute to point to a subclass of AutoField, e.g. 'django.db.models.BigAutoField'.
wagtail_localize.TemplateSegment: (models.W042) Auto-created primary key used when not defining a primary key type, by default 'django.db.models.AutoField'.
        HINT: Configure the DEFAULT_AUTO_FIELD setting or the WagtailLocalizeAppConfig.default_auto_field attribute to point to a subclass of AutoField, e.g. 'django.db.models.BigAutoField'.
wagtail_localize.Translation: (models.W042) Auto-created primary key used when not defining a primary key type, by default 'django.db.models.AutoField'.
        HINT: Configure the DEFAULT_AUTO_FIELD setting or the WagtailLocalizeAppConfig.default_auto_field attribute to point to a subclass of AutoField, e.g. 'django.db.models.BigAutoField'.
wagtail_localize.TranslationContext: (models.W042) Auto-created primary key used when not defining a primary key type, by default 'django.db.models.AutoField'.
        HINT: Configure the DEFAULT_AUTO_FIELD setting or the WagtailLocalizeAppConfig.default_auto_field attribute to point to a subclass of AutoField, e.g. 'django.db.models.BigAutoField'.
wagtail_localize.TranslationLog: (models.W042) Auto-created primary key used when not defining a primary key type, by default 'django.db.models.AutoField'.
        HINT: Configure the DEFAULT_AUTO_FIELD setting or the WagtailLocalizeAppConfig.default_auto_field attribute to point to a subclass of AutoField, e.g. 'django.db.models.BigAutoField'.
wagtail_localize.TranslationSource: (models.W042) Auto-created primary key used when not defining a primary key type, by default 'django.db.models.AutoField'.
        HINT: Configure the DEFAULT_AUTO_FIELD setting or the WagtailLocalizeAppConfig.default_auto_field attribute to point to a subclass of AutoField, e.g. 'django.db.models.BigAutoField'.
```
